version = 1

[[annotations]]
path = [
  "example/README.md",
  "go.mod",
  "go.sum",
]
SPDX-FileCopyrightText = "2025 Stanislav Zaprudskiy <stanislav.zaprudskiy@gmail.com>"
SPDX-License-Identifier = "Apache-2.0"
