# SPDX-FileCopyrightText: 2025 Stanislav Zaprudskiy <stanislav.zaprudskiy@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

{{- $spcName       := "my-openstack" -}}
{{- $spcSecretName := "my-openstack-auth" -}}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      name: demo-app
  template:
    metadata:
      labels:
        name: demo-app
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.repository }}"
        volumeMounts:
        - name: openstack-auth
          mountPath: "/openstack-auth"
          readOnly: true
        env:
        - name: OS_CLIENT_CONFIG_FILE
          value: /openstack-auth/secure-clouds.yaml
        - name: OS_CLOUD
          value: secrets-store-csi
      volumes:
      - name: openstack-auth
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "{{ $spcName }}"
          nodePublishSecretRef:
            name: "{{ $spcSecretName }}"

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ $spcName }}"
spec:
  provider: openstack
  parameters:
    # # Barbican secret - not yet implemented
    # secrets: |
    #   - fileName:        "<fileName>"
    #     secretReference: <URI|name|id>

    # # Keystone
    # applicationCredentials: |
    #   - fileName:     "<fileName>"
    #     template:     (Optional)
    #
    # # not yet implemented parameters
    #     name:         (Optional/Prefix)
    #     secret:       (Optional/rejected)
    #     description:  (Optional)
    #     expires_at:   (Optional/Duration)
    #     roles:        (Optional)
    #     access_rules: (Optional)
    #     unrestricted: (Optional)

    applicationCredentials: |
      - fileName: secure-clouds.yaml

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $spcSecretName }}"
data:
  {{- range  $k, $v := .Values.osAuth }}
  {{ $k }}: {{ $v | toString | b64enc }}
  {{- end }}
